# Generated by ./gen-hashes.sh script
{ javaVersionPlatform, ... }:
[
  {
    sha256 = {
      "11-linux-aarch64" = "13015mm664xgvzm20apf4i2psrk0nydrpavh4hxpw7w7wvakipxv";
      "11-linux-amd64" = "0w7lhvxm4nggqdcl4xrhdd3y6dqw9jhyca9adjkp508n4lqf1lxv";
      "11-darwin-amd64" = "0dnahicdl0vhrbiml9z9nbb7k75hbsjj8rs246i1lwril12dqb7n";
    }.${javaVersionPlatform} or null;
    url = "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/graalvm-ce-java${javaVersionPlatform}-21.2.0.tar.gz";
  }
  {
    sha256 = {
      "11-linux-aarch64" = "0rhi00jvg0nx451k74l7xj2fkgrqzwhsginal5vf747n32960vpd";
      "11-linux-amd64" = "1ybd7a6ii6582skr0nkxx7bccsa7gkg0yriql2h1lcz0rfzcdi3g";
    }.${javaVersionPlatform} or null;
    url = "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/native-image-installable-svm-java${javaVersionPlatform}-21.2.0.jar";
  }
  {
    sha256 = {
      "11-linux-amd64" = "1jszz97mkqavxzyhx5jxhi43kqjxk9c36j5l5hy3kn8sdfmbplm4";
      "11-darwin-amd64" = "1767ryhv2cn5anlys63ysax1p8ag79bykac1xfrjfan8yv6d8ybl";
    }.${javaVersionPlatform} or null;
    url = "https://github.com/oracle/truffleruby/releases/download/vm-21.2.0/ruby-installable-svm-java${javaVersionPlatform}-21.2.0.jar";
  }
  {
    sha256 = {
      "11-linux-aarch64" = "0vl6f8xx0nc4i8q4hjfcyk7qw520naqvq74k8f7wzmvhmnd3yirf";
      "11-linux-amd64" = "1ybjaknmbsdg8qzb986x39fq0h7fyiymdcigc7y86swk8dd916hv";
      "11-darwin-amd64" = "02dwlb62kqr4rjjmvkhn2xk9l1p47ahg9xyyfkw7im1jwlqmqnzf";
    }.${javaVersionPlatform} or null;
    url = "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/wasm-installable-svm-java${javaVersionPlatform}-21.2.0.jar";
  }
  {
    sha256 = {
      "11-linux-amd64" = "07759sr8nijvqm8aqn69x9vq7lyppns7a6l6xribv43jvfmwpfkl";
      "11-darwin-amd64" = "01l3as8dihc7xqy5sdkrpxmpzrqbcvvg84m2s6j1j8y2db1khf2s";
    }.${javaVersionPlatform} or null;
    url = "https://github.com/graalvm/graalpython/releases/download/vm-21.2.0/python-installable-svm-java${javaVersionPlatform}-21.2.0.jar";
  }
]
