#!/usr/bin/env nix-shell
#!nix-shell -p coreutils findutils gawk gnused jq nixUnstable -i bash

set -euo pipefail

readonly file="${1:-./resources/bin-names.nix}"
readonly out_path="$(nix --experimental-features 'nix-command flakes' build . --json --no-link | jq -r '.[0].outputs.out')"

{
    echo "# Generated by $(basename "$0") script"
    echo "["
    echo "${out_path}/bin/"* | tr " " "\n" | xargs -I '{}' basename '{}' | awk '{ printf "  \"%s\"\n", $0 }'
    echo "]"
} > "$file"
